Repository NASAWorldWind/WebWorldWind, pull requests merged in 2018-06, with the labels that each got.

#727 Move layer manager to the end of examples from Annotations to ParseURL
  examples/BlueMarbleTimeSeries.js
  examples/Collada.js
  examples/CustomPlacemark.js
  examples/GeoJSON.js
  examples/GeoTiffExample.js
  examples/GeographicMeshes.js
  examples/GeographicText.js
  examples/GoToLocation.js
  examples/Measurements.js
  examples/NDVIViewer.js
Labels: enhancement, nasa, needs review

#728 Move layer manager to the end of examples (from Paths to WMTS)
  examples/Paths.js
  examples/PickAllShapesInRegion.js
  examples/PlacemarksAndPicking.js
  examples/Polygons.js
  examples/RefreshImagery.js
  examples/ScreenImage.js
  examples/ScreenText.js
  examples/StarField.js
  examples/SunSimulation.js
  examples/SurfaceImage.js
  examples/SurfaceShapes.js
  examples/TestMovingSurfaceShapes.js
  examples/TriangleMeshes.js
  examples/WMS.js
  examples/WMTS.js
Labels: enhancement, nasa, needs review

#732 Simplified placemark position assignment. Corrected comment typo.
  examples/CustomPlacemark.js
Labels: enhancement, nasa, needs review

#731 Readability and documentation enhancements in five examples
  .idea/runConfigurations/GeoTiff.xml
  .idea/runConfigurations/GeoTiffExample.xml
  .idea/runConfigurations/KML.xml
  .idea/runConfigurations/KmlExample.xml
  examples/GeoTiff.html
  examples/GeoTiff.js
  examples/GoToLocation.js
  examples/KML.html
  examples/KML.js
  examples/Paths.js
  examples/RefreshImagery.js
  examples/SurfaceImage.js
Labels: enhancement, nasa, needs review

#660 Add a reader for AAIGrid
  karma.conf.js
  src/WorldWind.js
  src/formats/aaigrid/AAIGridConstants.js
  src/formats/aaigrid/AAIGridMetadata.js
  src/formats/aaigrid/AAIGridReader.js
  test/formats/aaigrid/AAIGridReader.test.js
  test/formats/aaigrid/aaigrid-tile.asc
Labels: esa, needs review, new feature

#752 Clarification for ScreenText Example
  examples/ScreenText.js
Labels: enhancement, nasa, needs review

#750 Improvements to documentation in 3 examples
  .idea/runConfigurations/WKT.xml
  examples/Shapefiles.js
  examples/TriangleMeshes.js
  examples/WKT.html
  examples/WKT.js
Labels: enhancement, nasa, needs review

#691 Add the notion of measured locations
  src/WorldWind.js
  src/geom/MeasuredLocation.js
Labels: esa, needs review, new feature

#757 Fix inconsistencies in the documentation of Location
  src/geom/Location.js
Labels: enhancement, esa, needs review

#758 Enhanced Cartesian surface normal precision
  src/globe/Globe.js
Labels: enhancement, nasa, needs review

#755 Rollback screen credit hyperlink support
  src/BasicWorldWindowController.js
Labels: bug, nasa, needs review

#735 Improvements on clarity and documentation for 5 examples
  examples/GeoJSONExporter.js
  examples/Measurements.js
  examples/Paths.js
  examples/PickAllShapesInRegion.js
  examples/SurfaceShapes.js
Labels: enhancement, nasa, needs review

#754 Corrected examples names in their HTML documents
  examples/BlueMarbleTimeSeries.html
  examples/DigitalGlobe.html
  examples/GeoJSONExporter.html
  examples/ParseUrlArguments.html
  examples/SimplestExample.html
  examples/Standalone.html
  examples/TestMovingSurfaceShapes.html
  examples/WKT.html
  examples/WktExporter.html
Labels: enhancement, needs review

#762 Moved NDVIViewer from 'Examples' to 'Apps' folder
  apps/NDVIViewer.html
  apps/NDVIViewer/CanvasWorker.js
  apps/NDVIViewer/NDVIViewer.js
  apps/NDVIViewer/analyticalSurfaces.json
  apps/NDVIViewer/app.js
  apps/util/LayerManager.js
Labels: enhancement, needs review

#753 StarField example refactored as "Night Sky Animation"
  .idea/runConfigurations/NightSkyAnimation.xml
  .idea/runConfigurations/SunSimulation.xml
  examples/NightSkyAnimation.html
  examples/NightSkyAnimation.js
  examples/StarField.html
  examples/StarField.js
  examples/SunSimulation.js
Labels: enhancement, needs review

#763 Add urn:ogc:def:crs:EPSG::4326 as alias for EPSG:4326 in GeoJSONParser
  src/formats/geojson/GeoJSONParser.js
Labels: enhancement, esa, needs review

#764 Refactored ScreenText Example
  examples/ScreenText.js
Labels: bug, enhancement, nasa, needs review

#765 Repaired BlueMarbleTimeSeries Examples
  examples/BlueMarbleTimeSeries.js
Labels: bug, enhancement, needs review
