Repository NASAWorldWind/WebWorldWind, pull requests merged in 2018-02, with the labels that each got.

#232 Clone the color object when creating a new set of attributes from an existing one
  src/shapes/AnnotationAttributes.js
  src/shapes/PlacemarkAttributes.js
  src/shapes/ShapeAttributes.js
  src/shapes/TextAttributes.js
Labels: enhancement, needs review

#441 Improve presentation of the list of elements in the KML example
  examples/KmlExample.html
  examples/KmlExample.js
  src/formats/kml/controls/KmlTreeVisibility.js
Labels: enhancement, needs review

#439 Add names to all KML elements in the example in order to hide random GUID
  examples/data/KML_Samples.kml
Labels: bug, needs review

#463 Repair PickedObjectList.topPickedObject
  src/pick/PickedObjectList.js
Labels: needs review

#465 Addressed text texture re-rendering according to cached contents
  src/render/DrawContext.js
  src/render/ScreenCreditController.js
  src/shapes/Annotation.js
  src/shapes/Placemark.js
  src/shapes/Text.js
Labels: bug, needs review

#470 Apply layer opacity to surface shapes
  src/shapes/SurfaceShape.js
  src/shapes/SurfaceShapeTile.js
Labels: needs review

#472 Fix layer opacity application to renderables
  src/shapes/AbstractMesh.js
  src/shapes/Annotation.js
  src/shapes/Path.js
  src/shapes/Placemark.js
  src/shapes/Polygon.js
  src/shapes/ScreenImage.js
Labels: needs review

#455 Align implementation of layer utility methods in WorldWindow
  src/WorldWindow.js
Labels: enhancement, needs review

#474 Update CSS Color String calculation and use
  src/render/TextRenderer.js
  src/shapes/SurfaceShape.js
  src/util/Color.js
  test/util/Color.test.js
Labels: needs review

#269 Fix GeoJSON parser for polygons with multiple linear rings
  src/formats/geojson/GeoJSONGeometryPolygon.js
  src/formats/geojson/GeoJSONParser.js
Labels: needs review

#267 Add option for configuring the resampling mode of surface images
  examples/SurfaceImage.js
  examples/data/surface-image-nearest.png
  src/WorldWind.js
  src/cache/GpuResourceCache.js
  src/render/Texture.js
  src/shapes/SurfaceImage.js
Labels: enhancement, needs review

#476 Update Open Street Map data source
  src/layer/OpenStreetMapImageLayer.js
Labels: needs review

#233 Add support for resources embedded in KMZ files
  examples/data/KML_Samples.kml
  examples/data/etna.kmz
  src/formats/kml/KmlFile.js
  src/formats/kml/KmlFileCache.js
  src/formats/kml/KmlLink.js
  src/formats/kml/KmlObject.js
  src/formats/kml/KmzFile.js
  src/formats/kml/README.MD
  src/formats/kml/controls/KmlTreeVisibility.js
  src/formats/kml/features/KmlFeature.js
  src/formats/kml/features/KmlGroundOverlay.js
  src/formats/kml/features/KmlNetworkLink.js
  src/formats/kml/features/KmlPlacemark.js
  src/formats/kml/features/KmlScreenOverlay.js
  src/formats/kml/geom/KmlLineString.js
  src/formats/kml/geom/KmlPolygon.js
  src/formats/kml/styles/KmlIconStyle.js
  src/formats/kml/styles/KmlListStyle.js
  src/formats/kml/styles/KmlStyle.js
  src/formats/kml/styles/KmlStyleMap.js
  src/formats/kml/util/HrefResolver.js
  src/formats/kml/util/ItemIcon.js
  src/formats/kml/util/NetworkLinkControl.js
  src/formats/kml/util/Pair.js
  src/formats/kml/util/StyleResolver.js
  src/util/jszip.js
  test/formats/kml/KmlIcon.test.js
  test/formats/kml/KmlLink.test.js
  test/formats/kml/styles/KmlIconStyle.test.js
  test/formats/kml/util/ItemIcon.test.js
Labels: enhancement, needs review

#438 Reduce severity of message about the lack of KML style
  src/formats/kml/util/StyleResolver.js
Labels: bug, needs review

#448 Add loading spinner to the GeoTIFF example
  examples/GeoTiffExample.html
  examples/GeoTiffExample.js
Labels: enhancement, needs review

#477 Change textBaseline to bottom for text rendering
  src/render/TextRenderer.js
Labels: needs review

#480 Refine OSM attribution
  src/layer/OpenStreetMapImageLayer.js
Labels: needs review

#487 Move copyright symbol on OSM layer
  src/layer/OpenStreetMapImageLayer.js
Labels: needs review

#488 Add the EOX based OpenStreetMapImageLayer to BasicExample
  examples/BasicExample.js
Labels: enhancement, needs review
