Repository NASAWorldWind/WebWorldWind, pull requests merged in 2018-08, with the labels that each got.

#783 README adjustments
  README.md
Labels: enhancement, needs review

#784 Suppress automated API doc deployment
  .travis.yml
Labels: bug, needs review

#628 Heatmap Layer
  .idea/runConfigurations/examples_HeatMap.xml
  examples/HeatMap.html
  examples/HeatMap.js
  src/WorldWind.js
  src/layer/heatmap/HeatMapColoredTile.js
  src/layer/heatmap/HeatMapIntervalType.js
  src/layer/heatmap/HeatMapLayer.js
  src/layer/heatmap/HeatMapTile.js
Labels: esa, needs review, new feature

#785 Readme adjustments
  README.md
Labels: enhancement, needs review
