Repository NASAWorldWind/WebWorldWind, pull requests merged in 2018-05, with the labels that each got.

#652 Add elevation config property to WcsCoverage
  src/ogc/wcs/WcsCapabilities.js
  src/ogc/wcs/WcsCoverage.js
  src/ogc/wcs/WcsCoverageDescriptions.js
  src/ogc/wcs/WcsUrlBuilder.js
  src/util/Logger.js
  src/util/WcsTileUrlBuilder.js
  test/ogc/wcs/WcsCapabilities.test.js
  test/ogc/wcs/WcsCoverage.test.js
  test/ogc/wcs/WcsUrlBuilder.test.js
Labels: needs review, new feature

#661 Replacement of Bing logo image credit for a ScreenImage
  src/layer/BingTiledImageLayer.js
Labels: needs review

#662 Removed image credits to give precedence to text-based ones.
  src/layer/DigitalGlobeTiledImageLayer.js
  src/layer/OpenStreetMapImageLayer.js
  src/render/ScreenCreditController.js
Labels: needs review

#641 Prioritized elevation coverage selection
  src/globe/ElevationModel.js
  src/globe/Tessellator.js
  test/globe/ElevationModel.test.js
Labels: enhancement, needs review

#663 Added capability to modify Bing logo positioning and alignment
  src/layer/BingTiledImageLayer.js
Labels: enhancement, needs review

#690 Avoided drawing of multiple Bing logos using static member
  src/WorldWind.js
  src/layer/BingTiledImageLayer.js
Labels: bug, needs review

#693 Add TileMatrix/TileMatrixSet
  src/geom/TileMatrix.js
  src/geom/TileMatrixSet.js
  src/util/Logger.js
  test/geom/TileMatrix.test.js
  test/geom/TileMatrixSet.test.js
Labels: needs review, new feature

#651 Improve the GeoJSON example
  examples/GeoJSON.js
Labels: enhancement, needs review

#697 New layout for screen credits
  src/render/ScreenCreditController.js
Labels: enhancement, needs review

#708 Slight correction to Annotations example's comments
  examples/Annotations.js
Labels: enhancement, needs review

#707 Added comments to BasicExample
  examples/BasicExample.js
Labels: enhancement, needs review

#709 Commented boilerplate code for examples (from Paths to WMTS).
  examples/Paths.js
  examples/PickAllShapesInRegion.js
  examples/PlacemarksAndPicking.js
  examples/Polygons.js
  examples/RefreshImagery.js
  examples/ScreenImage.js
  examples/ScreenText.js
  examples/Shapefiles.js
  examples/Standalone.html
  examples/StarField.js
  examples/SurfaceImage.js
  examples/SurfaceShapes.js
  examples/TestMovingSurfaceShapes.js
  examples/TriangleMeshes.js
  examples/WMS.js
  examples/WMTS.js
  examples/Wkt.js
  examples/WktExporter.js
Labels: enhancement, needs review

#710 Commented boilerplate code for examples (from Annotations to ParseURLArgs).
  examples/Annotations.js
  examples/Atmosphere.js
  examples/BlueMarbleTimeSeries.js
  examples/Collada.js
  examples/Configuration.js
  examples/CustomPlacemark.js
  examples/DeepPicking.js
  examples/DigitalGlobe.js
  examples/GeoJSON.js
  examples/GeoJSONExporter.js
  examples/GeoTiffExample.js
  examples/GeographicMeshes.js
  examples/GeographicText.js
  examples/GoToLocation.js
  examples/KmlExample.js
  examples/Measurements.js
  examples/MultiWindow.js
  examples/NDVIViewer.js
  examples/ParseUrlArguments.js
Labels: needs review

#711 Corrected logger level comment in examples
  examples/Annotations.js
  examples/BasicExample.js
  examples/BlueMarbleTimeSeries.js
  examples/Collada.js
  examples/Configuration.js
  examples/CustomPlacemark.js
  examples/DeepPicking.js
  examples/DigitalGlobe.js
  examples/GeoJSON.js
  examples/GeoJSONExporter.js
  examples/GeoTiffExample.js
  examples/GeographicMeshes.js
  examples/GeographicText.js
  examples/GoToLocation.js
  examples/KmlExample.js
  examples/Measurements.js
  examples/MultiWindow.js
  examples/ParseUrlArguments.js
  examples/PickAllShapesInRegion.js
  examples/PlacemarksAndPicking.js
  examples/RefreshImagery.js
  examples/ScreenText.js
  examples/Shapefiles.js
  examples/Standalone.html
  examples/StarField.js
  examples/SunSimulation.js
  examples/SurfaceShapes.js
  examples/TestMovingSurfaceShapes.js
  examples/WMS.js
  examples/WMTS.js
  examples/Wkt.js
  examples/WktExporter.js
Labels: enhancement, needs review

#714 Enhanced geographic to Cartesian arithmetic precision
  src/WorldWind.js
  src/globe/Globe.js
  src/projections/GeographicProjection.js
  src/projections/ProjectionWgs84.js
  test/CustomMatchers.test.js
  test/WorldWindow.test.js
  test/geom/Matrix.test.js
  test/globe/Globe.test.js
  test/globe/ProjectionWgs84.test.js
  test/render/DrawContext.test.js
Labels: enhancement, needs review

#717 Added general descriptions to examples that were lacking one
  examples/PickAllShapesInRegion.js
  examples/Shapefiles.js
  examples/StarField.js
  examples/SunSimulation.js
  examples/TestMovingSurfaceShapes.js
  examples/TriangleMeshes.js
  examples/WMS.js
  examples/WMTS.js
  examples/Wkt.js
  examples/WktExporter.js
Labels: enhancement, nasa, needs review

#718 Add descriptions to examples from Annotations to ParseURL
  examples/Annotations.js
  examples/BasicExample.js
  examples/Collada.js
  examples/DigitalGlobe.js
  examples/GeoJSON.js
  examples/GeoTiffExample.js
  examples/KmlExample.js
  examples/Measurements.js
  examples/NDVIViewer.js
  examples/ParseUrlArguments.js
Labels: enhancement, nasa, needs review

#715 Improved documentation for ParsingURLArguments and Custom Placemarks Examples
  examples/CustomPlacemark.js
  examples/ParseUrlArguments.js
Labels: enhancement, nasa, needs review

#716 Documentation improvement of four examples
  examples/Collada.js
  examples/DeepPicking.js
  examples/GeographicMeshes.js
  examples/GeographicText.js
Labels: enhancement, nasa, needs review
