Repository NASAWorldWind/WebWorldWind, pull requests merged in 2018-03, with the labels that each got.

#500 Corrected comparison operators that may introduce type coercion
  src/layer/CoordinatesDisplayLayer.js
  src/layer/FrameStatisticsLayer.js
  src/shapes/ScreenText.js
  src/util/Offset.js
Labels: enhancement, needs review

#446 Remove leftover code in the GeoTIFF parser
  src/formats/geotiff/GeoTiffReader.js
  src/formats/geotiff/GeoTiffUtil.js
Labels: needs review

#447 Add support for the projLinearUnits GeoKey in GeoTIFF
  src/formats/geotiff/GeoTiffMetadata.js
  src/formats/geotiff/GeoTiffReader.js
Labels: needs review

#505 Fix text texture cache usage in DrawContext
  src/render/DrawContext.js
Labels: needs review

#499 Refactored ScreenCreditsController to use existing components
  src/WorldWindow.js
  src/render/ScreenCreditController.js
  test/BasicWorldWindowController.test.js
  test/WorldWindow.test.js
  test/render/DrawContext.test.js
Labels: enhancement, needs review

#507 Repair Placemark opacity and clarify property documentation
  src/shapes/Placemark.js
Labels: needs review

#496 Repaired multi-window user input navigation
  src/BasicWorldWindowController.js
Labels: needs review

#502 Allow setting a canvas element instead of the ID of a canvas when creating a WorldWindow
  src/WorldWindow.js
Labels: enhancement, needs review

#533 Network request throttling
  src/WorldWind.js
  src/layer/TiledImageLayer.js
  src/layer/WmtsLayer.js
Labels: needs review

#532 Improve GPU resource cache management
  src/cache/GpuResourceCache.js
  src/cache/MemoryCache.js
  src/render/DrawContext.js
  src/shapes/SurfaceShapeTile.js
Labels: needs review

#493 Add GeoTiff parsing to ElevationModel and WcsEarthElevationModel
  examples/GeoTiffExample.js
  karma.conf.js
  src/WorldWind.js
  src/formats/geotiff/GeoTiffReader.js
  src/globe/ElevationModel.js
  src/util/Logger.js
  test/formats/geotiff/GeoTiffReader.test.js
  test/formats/geotiff/grayscale-test.tif
  test/formats/geotiff/rgb-test.tif
Labels: needs review

#535 Adjusted the referral link in BingImageryUrlBuilder
  src/util/BingImageryUrlBuilder.js
Labels: needs review

#534 Elevation tile request throttling
  src/WorldWind.js
  src/globe/ElevationModel.js
Labels: enhancement, needs review

#536 Increase WMTS tile matrix cache size
  src/layer/WmtsLayer.js
Labels: enhancement, needs review

#546 Fix layer reference for ordered rendering
  src/WorldWindow.js
  src/formats/collada/ColladaScene.js
  src/shapes/AbstractMesh.js
  src/shapes/Annotation.js
  src/shapes/Path.js
  src/shapes/Polygon.js
Labels: needs review

#547 Repaired unit tests erroneously modifying Vec3.ZERO
  test/geom/Line.test.js
  test/geom/Matrix.test.js
  test/geom/Vec3.test.js
Labels: bug, needs review

#548 Modified BoundingBox.setToSector to handle large sectors
  src/geom/BoundingBox.js
  test/CustomMatchers.test.js
  test/geom/BoundingBox.test.js
Labels: needs review

#400 Add an exporter for WKT
  examples/WktExporter.html
  examples/WktExporter.js
  src/WorldWind.js
  src/formats/wkt/WktExporter.js
Labels: needs review

#576 Addition of screen credit hyperlink support
  src/BasicWorldWindowController.js
  src/layer/BingTiledImageLayer.js
  src/layer/DigitalGlobeTiledImageLayer.js
  src/layer/OpenStreetMapImageLayer.js
  src/render/ScreenCreditController.js
Labels: enhancement, needs review

#581 Add WCS GetCapabilities and DescribeCoverage parsers
  karma.conf.js
  src/WorldWind.js
  src/ogc/gml/GmlBoundedBy.js
  src/ogc/gml/GmlDomainSet.js
  src/ogc/gml/GmlRectifiedGrid.js
  src/ogc/ows/OwsBoundingBox.js
  src/ogc/ows/OwsDatasetSummary.js
  src/ogc/ows/OwsKeywords.js
  src/ogc/ows/OwsServiceIdentification.js
  src/ogc/wcs/WcsCapabilities.js
  src/ogc/wcs/WcsDescribeCoverage.js
  src/util/Logger.js
  test/ogc/wcs/WcsCapabilities.test.js
  test/ogc/wcs/WcsDescribeCoverage.test.js
  test/ogc/wcs/wcs100DescribeCoverage.xml
  test/ogc/wcs/wcs100GetCapabilities.xml
  test/ogc/wcs/wcs201DescribeCoverage.xml
  test/ogc/wcs/wcs201GetCapabilities.xml
Labels: needs review

#578 Accept plain JS objects as data source for the GeoJSON parser
  src/formats/geojson/GeoJSONParser.js
Labels: enhancement, needs review
